In [35]:
import pandas as pd
import numpy as np

words = pd.read_csv("word_list.csv")

In [36]:
words.head()

   freq  syl  let       word  imag  conc  meaning  list  id
0   100    1    3        lip  6.57  6.93     5.32     1   1
1    19    3    7    nursery  6.10  6.45     7.40     1   2
2    20    1    3        ink  6.37  6.87     6.96     1   3
3    50    3    8   evidence  3.23  3.45     6.20     1   4
4     1    2    9  limelight  4.83  3.06     4.72     1   5

In [38]:
n = len(words)
print "total words:" , n

words_240 = np.random.choice(words["id"],size=240, replace=False)
words_120 = np.random.choice(words_240,size=120, replace=False)

total words: 898

In [40]:
print words_240
print
print words_120

final = words[words["id"].isin(words_240)].copy()

[404 160 165  90 767 539 373 192 284 368 399  48 180 121  38 579 662 801
 162  66  69 297  45 589 123 571 184 763 847 153 242 236 338 881 619 615
 700 599 641 654 723 370 451 102 334 473 649 145  82 350 298 498 697  20
 333 869 424 839 380 147 354 482 672 675 705 855 435 444 222 224 235 245
 640 526 593 255 717 681 166 131 317 580 870 814 549 878 608  70 487 578
 157  59 688 199 747 246 695 486 168  92  17 500  19 256 130  42 283 481
 758 172 420  73 739 630 872 335 507 704 588 321 575 177 100 122 390 220
 410 393  75 798 891 595 543 141 442 239 494 254 369 663 856 471  61 833
 194 348 794 859 252 658 214 759  51 582 709 898 585 581 653 115 238 379
 495 555 468 810 357 731 418 719 699 566 851 148 703  26 270 715 231  34
 465   5 642 391  29 119 548 206 360 563 332 680 875 489 645 775 217 586
 827 346 564 587 340  56 762 295 721 516  80 173  57 601 387 735 743   3
 477 423 868 416 737  77 635 113 733 574   2 437 344 741 381 756  54 475
 510 201 417 466 296 225]

[870 465 444 147 192 703 477 238 763 741 437 360 539 510 184 869 417 373
 697 681 601 357  57 141 715 588 390 543 672  92 399  77 827 121 487  19
 801 564 739  29 481 498 482 298 767 387 859 348 284 495 256 344 580  80
 391 641 868 700 471 737 878 424 317 225 473 231 222  38 680 688 587 833
 165 855 468 295 157 585 881 333 370 608 794 675 654 177 283 555 735 704
 354  69   2 743 847 410 758 340 321 420 393 759  82 119 172 236 418 775
  61 589 699 733 180 839 756 709 369 856 246 575]

In [41]:
final["is_shown"] = 0

In [42]:
final.head()

    freq  syl  let       word  imag  conc  meaning  list  id  is_shown
1     19    3    7    nursery  6.10  6.45     7.40     1   2         0
2     20    1    3        ink  6.37  6.87     6.96     1   3         0
4      1    2    9  limelight  4.83  3.06     4.72     1   5         0
16     3    4    8   immunity  3.43  2.46     5.76     1  17         0
18     2    3    9  obsession  3.87  1.65     4.16     1  19         0

In [50]:
ids = list(final["id"])
is_shown = list(final["is_shown"])

for x in range(0,239):
    #print x, ids[x], is_shown[x]
    if ids[x] in words_120:
        is_shown[x] = 1

final["is_shown"] = is_shown

In [51]:
len(is_shown)

240

In [52]:
sum(is_shown)

120

In [46]:
final

     freq  syl  let          word  imag  conc  meaning  list   id  is_shown
1      19    3    7       nursery  6.10  6.45     7.40     1    2         1
2      20    1    3           ink  6.37  6.87     6.96     1    3         0
4       1    2    9     limelight  4.83  3.06     4.72     1    5         0
16      3    4    8      immunity  3.43  2.46     5.76     1   17         0
18      2    3    9     obsession  3.87  1.65     4.16     1   19         1
19      2    2    9     horsehair  5.67  6.80     6.20     1   20         0
25      1    3    9     charlatan  3.43  5.28     3.19     1   26         0
28      1    4   10    exactitude  2.23  1.69     3.00     1   29         1
33     28    3   10    profession  3.83  3.65     5.44     1   34         0
37     23    2    5         drama  4.90  3.66     7.00     1   38         1
41     17    3    8      reminder  2.83  3.48     5.20     1   42         0
44     50    1    3           fun  5.23  2.45     5.50     1   45         0
47     50    3    8      occasion  2.53  3.22     5.00     1   48         0
50    100    1    5         truth  2.73  1.69     4.78     1   51         0
53     50    2    6        coffee  6.73  6.89     7.28     1   54         0
55      9    3    7       robbery  5.00  4.75     6.16     1   56         0
56     19    2    5         panic  5.33  2.18     6.72     1   57         1
58     29    3   10    substitute  3.13  4.56     4.48     1   59         0
60     27    1    4          chin  6.43  6.96     5.28     1   61         1
65      6    2    7       phantom  5.03  2.50     5.00     1   66         0
68     32    2    6        barrel  6.57  6.94     6.16     1   69         1
69      8    2    7       essence  2.33  1.66     3.28     1   70         0
72    100    4    8      material  5.07  6.10     5.92     1   73         0
74      4    1    5         wench  5.30  6.20     5.08     1   75         0
76      6    1    5         chasm  4.47  5.25     6.04     1   77         0
79     35    3    8      elephant  6.83  7.00     6.88     1   80         0
81      1    4    9     infirmary  5.63  6.43     6.65     1   82         0
89     22    3    9     ignorance  3.57  1.75     4.00     1   90         0
91     26    2    4          item  3.67  5.27     4.96     1   92         0
99     45    1    5         grief  4.70  1.86     6.32     1  100         0
..    ...  ...  ...           ...   ...   ...      ...   ...  ...       ...
746     3    2    7       shotgun  6.60  6.96     7.88     1  747         0
755     1    2    6        icebox  6.17  6.90     6.28     1  756         0
757    50    2    7       fortune  4.57  3.82     6.00     1  758         0
758     1    3   11   subtraction  3.80  3.73     5.52     1  759         0
761    50    5   10    university  6.53  5.87     7.20     1  762         0
762     2    2    6        hurdle  6.33  6.65     5.92     1  763         0
766    32    2    6        cellar  6.27  6.83     6.79     1  767         0
774    22    4    7       anxiety  4.03  1.63     5.69     1  775         0
793    25    2    7       painter  5.87  6.59     6.40     1  794         0
797    29    2    8      twilight  5.93  5.77     6.56     1  798         0
800    50    3    6        potato  6.50  7.00     7.13     1  801         0
809     2    3    9     diffusion  3.40  3.18     5.67     1  810         0
813   100    1    3           boy  6.57  6.93     6.96     1  814         0
826    20    2    7       charter  3.83  5.05     4.89     1  827         0
832    22    2    6        salute  5.77  5.00     6.52     1  833         0
838     2    2    6        deluge  4.57  4.38     5.32     1  839         0
846     1    4   10    unbeliever  2.60  4.00     4.72     1  847         0
850   100    1    5         house  6.67  6.93     6.83     1  851         0
854    22    3   10    permission  2.87  4.43     4.68     1  855         0
855    20    2    8      hillside  6.30  6.59     6.92     1  856         0
858   100    1    3           sea  6.73  6.79     7.16     1  859         0
867    23    3   12  headquarters  5.03  5.94     5.08     1  868         0
868     5    2    6        poster  6.33  6.96     6.20     1  869         0
869     8    3    7       utensil  5.47  6.58     6.08     1  870         0
871    50    2    6        prison  6.23  6.62     7.21     1  872         0
874    23    3   10    restaurant  6.47  6.83     6.88     1  875         0
877    21    1    4          vest  6.37  6.73     5.96     1  878         0
880     1    2    7       doorman  6.40  6.52     6.28     1  881         0
890    29    2    6        beggar  6.40  6.25     6.50     1  891         0
897    19    2    9     fireplace  6.83  6.96     7.08     1  898         0

[240 rows x 10 columns]